### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "login":"dodik2@mail.com",
  "password":"kuku"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "login":"dodik2@mail.com",
  "password":"kuku"
}